### ISSUE TITLE
Scanning for BLE devices (5s) ... just repeats

### ISSUE THREAD

**Issue by vshymanskyy** [adafruit/Adafruit_BLESniffer_Python#12]
```
Connecting to sniffer on COM16
Scanning for BLE devices (5s) ...
Scanning for BLE devices (5s) ...
Scanning for BLE devices (5s) ...
```
It doesn't display device list. In the logs I see:
```
02-Mar-2017 13:23:18 (FLE Standard Time) ERROR: 
Traceback (most recent call last):
  File "Adafruit_BLESniffer_Python-master\SnifferAPI\Packet.py", line 161, in getPacket
    packetList = self.decodeFromSLIP(timeout)
  File "Adafruit_BLESniffer_Python-master\SnifferAPI\Packet.py", line 138, in decodeFromSLIP
    raise Exceptions.UARTPacketError("Unexpected character after SLIP_ESC: %d." % serialByte)
UARTPacketError: Unexpected character after SLIP_ESC: 62.
02-Mar-2017 13:23:18 (FLE Standard Time) ERROR: CRASH
Traceback (most recent call last):
  File "Adafruit_BLESniffer_Python-master\SnifferAPI\Sniffer.py", line 150, in run
    self.runSniffer()
  File "Adafruit_BLESniffer_Python-master\SnifferAPI\Sniffer.py", line 175, in runSniffer
    self._continuouslyPipe()
  File "Adafruit_BLESniffer_Python-master\SnifferAPI\SnifferCollector.py", line 153, in _continuouslyPipe
    if not packet.valid:
AttributeError: 'NoneType' object has no attribute 'valid'
```
I'm using Windows 10 x64. FW 1111

**Comment by vshymanskyy** [comment]
Also, sometimes, I get:
```
02-Mar-2017 13:28:24 (FLE Standard Time) ERROR: packet creation error
Traceback (most recent call last):
  File "Adafruit_BLESniffer_Python-master\SnifferAPI\Packet.py", line 308, in __init__
    self.readStaticHeader(packetList)
  File "Adafruit_BLESniffer_Python-master\SnifferAPI\Packet.py", line 328, in readStaticHeader
    self.protover = packetList[PROTOVER_POS]
IndexError: list index out of range
```

**Comment by vshymanskyy** [comment]
Ok, fixed on my fork... https://github.com/vshymanskyy/BLESniffer_Python
